language: minimal
env:
  global:
  - VERSION="1.0.$TRAVIS_BUILD_NUMBER"
  - secure: qYAbWBTP3mz4b+XCUAHkPdf6Xabs/omkFTH3Q5JWq2T6KAqFPx0+ns7WF/HQjTBz4zGsqNNGCmQy/DAiF2wqJmOizPUSNFBbF7SRWBQshq8XoEWn5SoPZCrqxYdIyrVTAhziRhDQxDBL7N6f26E4oM8bBp+GDyUPLwQfjCLV09TOME/OqK9gmjvdyfsyaEMmZrsjW1xp94GUaKO8GLarCckFMOTD0tMgA+63LfgBOEAt6phNRWYeow1LaSDt4ZKCyCplDj1ZhA4CyfFV1lVfRoP7M1cufZqTlAns2m6grwg4NxcqaPaYAQtnEKdOCJuMu0csrDAvgccBBgLVWx+YYOgGn5jBG021Ls9G4HhAmYXc2UvbAdfD6mnoPvMuITWEn9SMYzjwjDHVcYULvTjRqA+402+CpWAM3C7Om7aum3r0HCy60UHUGb8ZGMJAeV8ccTrQ/6MHEPdSDjd8zBIFnUlSkkFyHjxUpcT12mWK3FBbnhKPxVAViV7VxsHr2BahsSDMOOoiMd00vJQpEqpDCQfv0inRy34N5Fvs2JajtnbDkr0y3x3qr4T+7AfqE3Tw1gQLa4fYSJnTQ4M5GF8E0pvwUL9oop45mV+bsdntlYMoq/JuNFnXEkcp2JVvTY1cnZhIAmLXcfJ8VqCW+teicNR/x9Xjs54o5EddtSwRYUk=
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_e4f343148096_key -iv $encrypted_e4f343148096_iv
  -in deploy/kubeconfig.enc -out deploy/kubeconfig -d
install:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kubectl
  && chmod +x kubectl
- curl https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz | tar -xvz && mv linux-amd64/helm ./helm
script:
- docker build -t registry.smirlwebs.com/smirl/furniture-replications:$VERSION .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u smirl --password-stdin registry.smirlwebs.com
- docker push registry.smirlwebs.com/smirl/furniture-replications:$VERSION
deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    branch: master
