---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: furniture-replications
  namespace: furniture-replications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: furniture-replications
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: furniture-replications
    spec:
      containers:
      - image: "registry.smirlwebs.com/smirl/furniture-replications:{{ .Values.version }}"
        imagePullPolicy: Always
        name: furniture-replications
        ports:
        - containerPort: 80
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: amplify
              key: api_key
        - name: AMPLIFY_IMAGENAME
          value: 'furniture-replications'
      imagePullSecrets:
      - name: registry.smirlwebs.com
